#TypeError
from datetime import time
mytime = time(hour = '23')
